version: '3.8'

services:
  web_api:
    build:
      context: .
      dockerfile: ./WebApi/Dockerfile
    container_name: web_api
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=kestrel_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/RPGApi.pfx
      - "ConnectionStrings:RedisConnection=redis:6379"
      - "ConnectionStrings:GlobalPostgresConnection=Host=postgres;Database=postgres;Username=postgres;Password=postgres_password"
      - "ConnectionStrings:DatabaseConnection=Host=postgres;Database=rpg_api;Username=postgres;Password=postgres_password"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "rpg_api"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres_password"
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379